spring:
  application:
    name: umc-hackathon-spring

  profiles:
    active: dev

  # 데이터베이스 설정 (H2 인메모리)
  datasource:
    url: jdbc:mysql://localhost:3306/hack
    username: root
    password: cjswoshckd44!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false  # <-- 이거 추가

  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console



  # Thymeleaf 설정
  thymeleaf:
    cache: false

server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.umc: DEBUG