spring:
  application:
    name: divary-spring

  profiles:
    active: dev

  # 데이터베이스 설정 (H2 인메모리)
  datasource:
    url: jdbc:h2:mem:divary
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Thymeleaf 설정
  thymeleaf:
    cache: false

server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.divary: DEBUG

# 애플리케이션 커스텀 설정
app:
  jwt:
    secret: divarySecretKeyForJWTTokenGenerationAndValidation2024
    expiration: 86400000 # 24시간
