spring:
  application:
    name: umc-hackathon-spring

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false # <-- 이거 추가

  # Thymeleaf 설정
  thymeleaf:
    cache: false

server:
  port: 8080
jwt:
  secret: my-super-secret-jwt-key-that-is-very-long-256bit
