spring:
  application:
    name: umc-hackathon-spring

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false # <-- 이거 추가

  # Thymeleaf 설정
  thymeleaf:
    cache: false

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8080
jwt:
  secret: my-super-secret-jwt-key-that-is-very-long-256bit

# Google Drive 설정
google:
  drive:
    service-account-key-path: classpath:jovial-monument-432709-s0-5455a7338d58.json
    parent-folder-id: root
    application-name: UMC-Hackathon-Spring
